### ISSUE TITLE
Class 'TYPO3\CMS\Core\Domain\Repository\PageRepository' not found

### ISSUE THREAD

**Issue by novacore** [Hauer-Heinrich/hh_add_statuscode#1]
Hello! 

thanks for your extension. I got this error message on 9.5.15:

_Class 'TYPO3\CMS\Core\Domain\Repository\PageRepository' not found_

I fixed it by changing your ShortcutMiddlerware.php from:

use TYPO3\CMS\Core\Domain\Repository\PageRepository

to:

use TYPO3\CMS\Frontend\Page\PageRepository

**Comment by Teisi** [comment]
@novacore should be solved now with version 0.1.1
